version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - 27017:27017

  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - 6379:6379
